### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by akaneokada** [aknokd/furima_28309#9]
# URL
https://furima-28309.herokuapp.com/
# Basic認証のIDとパスワード
ID: admin
パスワード: 2222
# 出品者用のメールアドレスとパスワード
メールアドレス: test@example.com
パスワード: test11
# 購入者用のメールアドレスとパスワード
メールアドレス: test2@example.com
パスワード: test22
# 購入用カードの番号・期限・セキュリティコード
カード番号: 4242424242424242
期限: 3月/24年
セキュリティコード: 123

**Comment by mo1015** [comment]
岡田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
